### ISSUE TITLE
AttributeError: 'module' object has no attribute 'add_rectangles

### ISSUE THREAD

**Issue by violivei** [DrewNF/Tensorflow_Object_Tracking_Video#1]
Hello,

I'm testing your code for videos and when I executed the script train_multiclass.py to obtain the model, however it gives me the following error:

```
Traceback (most recent call last):
  File "TENSORBOX/train_multiclass.py", line 610, in <module>
    main()
  File "TENSORBOX/train_multiclass.py", line 607, in main
    train(H, test_images=[])
  File "TENSORBOX/train_multiclass.py", line 555, in train
    test_output_to_log = train_utils_multiclass.add_rectangles(H,
AttributeError: 'module' object has no attribute 'add_rectangles'

```

Is this expected?

Thanks in advance.

**Comment by DrewNF** [comment]
I update the project, knwo there is only one train file and you set the number of class in the hypes file, there's no difference between train on a single or multi class.
Hope this solve your problem.

**Comment by violivei** [comment]
Hello @DrewNF 

I saw your updates. Thanks a lot.
However, I'm having real issues trying to run this with multiclass images.

**Comment by DrewNF** [comment]
For know the multiclass recognize and draw rectangles on different objects but really don't recognize wich ones are.
I'm working to adapt inception to get the real label of the object.
This is an issue that i'm trying to solve. But I will realise it after the submission deadline of ImageNET :)
